### PR TITLE
rsyslog-relp and snmp

### PR DESCRIPTION
**Pull request by cmeissner**
## Before submitting your PR

  1. Open an **issue** and refer to its number in your PR title
  1. If it's a bug and you have the solution, go on with the PR! 
  1. If it's an enhancement, please wait for our feedback before starting to work on it
  1. Please run ```puppet-lint``` on your code and ensure it's compliant

## After submitting your PR

  1. Verify Travis checks and eventually fix the errors
  1. Feel free to ping us if we don't reply promptly

### CODE REVIEW

**Comment by alvagante** [comment]
Don't you like the current snmpd data? Should be the same of snmp, please use it (or eventually correct it)

**Comment by cmeissner** [comment]
smtpd and snmp are different things. So it's correct to provide these approach.

**Comment by alvagante** [comment]
Check this https://github.com/example42/tinydata/tree/master/data/snmpd doesn't it fit your needs?

**Comment by cmeissner** [comment]
Nope snmpd installs snmp daemon:

> Description: SNMP (Simple Network Management Protocol) agents
>  The Simple Network Management Protocol (SNMP) provides a framework
>  for the exchange of management information between agents (servers)
>  and clients.
>  .
>  The Net-SNMP agent is a daemon which listens for incoming SNMP
>  requests from clients and provides responses.

and snmp installs snmp applications:

> Description: SNMP (Simple Network Management Protocol) applications
>  The Simple Network Management Protocol (SNMP) provides a framework
>  for the exchange of management information between agents (servers)
>  and clients.
>  .
>  The Net-SNMP applications are a collection of command line clients
>  for issuing SNMP requests to agents.

So these are really different packages.

**Pull request merged**
